apiVersion: v1
kind: ReplicationController
metadata:
  name: java-nginx-rc
  namespace: test-ns
spec:
  replicas: 2
  selector:
    app: java-nginx
  template:
    metadata:
      name: javanginxpod
      labels:
        app: java-nginx
    spec:
      containers:
      - name: javacont
        image: dockerhandson/java-web-application:1
        ports:
        - containerPort: 8080
      - name: nginxcont
        image: nginx
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
 name: javanginxsvc
 namespace: test-ns
spec:
  type: NodePort
  selector:
    app: java-nginx
  ports:
  - port: 80
    targetPort: 80
    name: nginx
  - port: 8080
    targetPort: 8080
