apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx-rs
  namespace: test-ns
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      name: nginxpod
      labels: 
        app: nginx
    spec:
      containers:
      - name: nginxcont
        image: nginx
        ports:
        - containerPort: 80
---
apiVersion: v1 
kind: Service
metadata: 
  name: nginxsvc
  namespace: test-ns
spec: 
  type: NodePort
  selector:
    app: nginx
  ports:
  - port: 80
    targetPort: 80 