apiVersion: apps/v1
kind: DaemonSet
metadata: 
  name: nginxds
  namespace: test-ns
spec:
  selector:
    matchLabels:
      app: nginx
  template:
    metadata: 
      name: nginxpod
      labels:
        app: nginx
    spec:
      containers:
      - name: nginxcont
        image: nginx
        ports:
        - containerPort: 80