apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginxdep
  namespace: test-ns
spec:
  strategy:
    type: RollingUpdate
  minReadySeconds: 30
  replicas: 4
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      name: nginxpod
      labels:
        app: nginx
    spec:
      containers:
      - name: nginxcont
        image: nginx:stable-perl
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginxsvc
  namespace: test-ns
spec:
  type: NodePort
  selector:
    app: nginx
  ports:
  - port: 80
    targetPort: 80
