apiVersion: autoscaling/v2 
kind: HorizontalPodAutoscaler 
metadata:
  name: javahpa
  namespace: test-ns
spec:
  scaleTargetRef: 
    apiVersion: apps/v1
    kind: Deployment 
    name: javadep
  minReplicas: 2 
  maxReplicas: 3
  metrics:
  - type: Resource
    resource: 
      name: cpu
      target:
        type: Utilization
        averageUtilization: 40